export const enum collections {
  USER_COLLECTION = 'user',
  ADDRESS_COLLECTION = 'address',
  PRODUCT_COLLECTION = 'product',
  CART_COLLECTION = 'cart',
  WISHLIST_COLLECTION = 'wishlist',
  ORDER_COLLECTION = 'order',
  PAYMENT_COLLECTION = 'payment',
  COUPON_COLLECTION = 'coupon',
  NOTIFICATION_COLLECTION = 'notification',
  BRAND_COLLECTION = 'brand',
  STYLE_COLLECTION = 'style',
  BANNER_COLLECTION = 'banner',
  SESSION_COLLECTION = 'session',
}
